const express = require('express');
const app = express();
const cors = require('cors');
import {Request, Response} from 'express'
app.use(express.json());
app.use(cors({
    origin: 'http://localhost:3000'
}))

interface Cars {
    id: number
    name: string
    price: number
    image: string
    brand: string
    type: string
    topSpeed: number
    acceleration: string
    power: string
    description: string
    features: string[]
    specifications: {
      engine: string
      transmission: string
      drivetrain: string
      weight: string
      fuelEconomy: string
    }
  }
const fullData: Cars[] = [
    { id: 1, name: 'Ferrari LaFerrari', price: 1416362, image: 'https://www.williamloughran.co.uk//media/7431/ferrari-laferrari-2311-1.jpg?anchor=center&mode=crop&width=1400&height=675&rnd=133068622440000000', topSpeed: 217, acceleration: '0-60 mph in 2.4s', power: '950 hp', type: 'Hypercar', brand: 'Ferrari', description: 'The Ferrari LaFerrari is a hybrid hypercar offering cutting-edge performance and technology, blending electric motors with Ferrari’s F1-inspired V12 engine.', features: ['Hybrid Powertrain', 'Carbon-Fiber Body', 'F1-inspired KERS System'], specifications: { engine: '6.3L V12 Hybrid', transmission: '7-speed dual-clutch automatic', drivetrain: 'RWD', weight: '1585 kg', fuelEconomy: '17 mpg' } },
    { id: 2, name: 'Bugatti Chiron', price: 2990000, image: 'https://cdn.motor1.com/images/mgl/VzMq0z/s3/bugatti-chiron-1500.webp', topSpeed: 261, acceleration: '0-60 mph in 2.4s', power: '1,479 hp', type: 'Hypercar', brand: 'Bugatti', description: 'The Bugatti Chiron is a masterpiece of engineering, delivering unmatched speed and luxury with a quad-turbocharged W16 engine.', features: ['Quad-Turbocharged Engine', 'All-Wheel Drive', 'Luxurious Interior'], specifications: { engine: '8.0L W16', transmission: '7-speed dual-clutch', drivetrain: 'AWD', weight: '1995 kg', fuelEconomy: '9 mpg' } },
    { id: 3, name: 'Lamborghini Aventador', price: 393695, image: 'https://images.pistonheads.com/nimg/45077/AventadorSV_01.jpg', topSpeed: 217, acceleration: '0-60 mph in 2.9s', power: '730 hp', type: 'Supercar', brand: 'Lamborghini', description: 'The Lamborghini Aventador combines fierce performance with aggressive styling, powered by a naturally aspirated V12 engine.', features: ['V12 Engine', 'Aerodynamic Design', 'All-Wheel Drive'], specifications: { engine: '6.5L V12', transmission: '7-speed automated manual', drivetrain: 'AWD', weight: '1575 kg', fuelEconomy: '11 mpg' } },
    { id: 4, name: 'McLaren P1', price: 1150000, image: 'https://static.wixstatic.com/media/f2b0f7_7b0328ffbf9e43cd9d8e997594cc691d~mv2.jpg/v1/fill/w_5184,h_3456,al_c,q_90/2226-McLarenP1Bahrain.jpg', topSpeed: 217, acceleration: '0-60 mph in 2.8s', power: '903 hp', type: 'Hypercar', brand: 'McLaren', description: 'The McLaren P1 is a limited-production hybrid hypercar that exemplifies cutting-edge automotive technology and blistering performance.', features: ['Hybrid Powertrain', 'Active Aerodynamics', 'Lightweight Chassis'], specifications: { engine: '3.8L twin-turbo V8', transmission: '7-speed dual-clutch', drivetrain: 'RWD', weight: '1600 kg', fuelEconomy: '34 mpg' } },
    { id: 5, name: 'Porsche 918 Spyder', price: 845000, image: 'https://www.motoringresearch.com/wp-content/uploads/2021/07/001-Collecting-Cars-Porsche-918.jpg', topSpeed: 214, acceleration: '0-60 mph in 2.5s', power: '887 hp', type: 'Hybrid', brand: 'Porsche', description: 'The Porsche 918 Spyder is a high-performance hybrid sports car that blends exceptional speed with remarkable efficiency.', features: ['Hybrid Technology', 'All-Wheel Drive', 'Track Mode'], specifications: { engine: '4.6L V8', transmission: '7-speed PDK', drivetrain: 'AWD', weight: '1640 kg', fuelEconomy: '76 mpg' } },
    { id: 6, name: 'Koenigsegg Agera RS', price: 2550000, image: 'https://www.supervettura.com/blobs/Cars/96/03b61a3d-2433-4f46-b240-3eb193c1d68c.jpg?width=1920&height=1080&mode=crop', topSpeed: 278, acceleration: '0-60 mph in 2.8s', power: '1,160 hp', type: 'Hypercar', brand: 'Koenigsegg', description: 'The Koenigsegg Agera RS is a high-performance hypercar known for its speed and advanced technology.', features: ['Lightweight Construction', 'Aerodynamic Design', 'Twin-Turbocharged V8'], specifications: { engine: '5.0L twin-turbo V8', transmission: '7-speed dual-clutch', drivetrain: 'RWD', weight: '1400 kg', fuelEconomy: 'N/A' } },
    { id: 7, name: 'Pagani Huayra', price: 2600000, image: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Pagani%2C_GIMS_2019%2C_Le_Grand-Saconnex_%28GIMS0023%29.jpg', topSpeed: 238, acceleration: '0-60 mph in 2.8s', power: '730 hp', type: 'Hypercar', brand: 'Pagani', description: 'The Pagani Huayra is a blend of art and engineering, featuring a unique design and a powerful AMG V12 engine.', features: ['Artisan Craftsmanship', 'Active Aerodynamics', 'Carbon-Titanium Monocoque'], specifications: { engine: '6.0L twin-turbo V12', transmission: '7-speed automated manual', drivetrain: 'RWD', weight: '1360 kg', fuelEconomy: 'N/A' } },
    { id: 8, name: 'Aston Martin Valkyrie', price: 3000000, image: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Aston_Martin_Valkyrie_Verification_Prototype_001_Genf_2019_1Y7A5569.jpg', topSpeed: 250, acceleration: '0-60 mph in 2.5s', power: '1,160 hp', type: 'Hypercar', brand: 'Aston Martin', description: 'The Aston Martin Valkyrie is a track-focused hypercar that incorporates F1 technology and an aggressive design.', features: ['Hybrid Powertrain', 'F1-inspired Aerodynamics', 'Lightweight Carbon Fiber'], specifications: { engine: '6.5L naturally aspirated V12', transmission: '7-speed automated manual', drivetrain: 'RWD', weight: '1030 kg', fuelEconomy: 'N/A' } },
    { id: 9, name: 'Ford GT', price: 500000, image: 'https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/ford-gt_0.jpg?itok=-v3sPmZJ', topSpeed: 216, acceleration: '0-60 mph in 2.9s', power: '660 hp', type: 'Supercar', brand: 'Ford', description: 'The Ford GT is a modern supercar that combines cutting-edge technology with iconic design, inspired by the original GT40.', features: ['EcoBoost V6', 'Lightweight Construction', 'Track-focused Dynamics'], specifications: { engine: '3.5L twin-turbo V6', transmission: '7-speed dual-clutch', drivetrain: 'RWD', weight: '1420 kg', fuelEconomy: '20 mpg' } },
    { id: 10, name: 'Chevrolet Corvette ZR1', price: 123000, image: 'https://www.motortrend.com/files/66a166f50b6d640008357d7e/064-2025-chevrolet-corvette-zr1.jpg?w=768&width=768&q=75&format=webp', topSpeed: 212, acceleration: '0-60 mph in 2.8s', power: '755 hp', type: 'Supercar', brand: 'Chevrolet', description: 'The Chevrolet Corvette ZR1 is a powerful sports car that offers exceptional performance and handling.', features: ['Supercharged V8', 'Magnetic Ride Control', 'Aggressive Styling'], specifications: { engine: '6.2L supercharged V8', transmission: '7-speed manual', drivetrain: 'RWD', weight: '1525 kg', fuelEconomy: '15 mpg' } },
    { id: 11, name: 'Mercedes-AMG One', price: 2700000, image: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Mercedes-AMG_One_at_the_2022_Goodwood_Festival_of_Speed.jpg', topSpeed: 217, acceleration: '0-60 mph in 2.6s', power: '1,063 hp', type: 'Hypercar', brand: 'Mercedes-AMG', description: 'The Mercedes-AMG One brings F1 technology to the streets with its hybrid powertrain and aerodynamic design.', features: ['F1-inspired Hybrid System', 'Active Aerodynamics', 'Lightweight Structure'], specifications: { engine: '1.6L turbo V6 hybrid', transmission: '7-speed dual-clutch', drivetrain: 'AWD', weight: '1395 kg', fuelEconomy: 'N/A' } },
    { id: 12, name: 'Ferrari SF90 Stradale', price: 625000, image: 'https://f1rstmotors.com/_next/image?url=https%3A%2F%2Ff1rst-motors.s3.me-central-1.amazonaws.com%2Fblog%2F1714734880903-blob&w=3840&q=100', topSpeed: 211, acceleration: '0-60 mph in 2.5s', power: '986 hp', type: 'Hybrid', brand: 'Ferrari', description: 'The Ferrari SF90 Stradale is a high-performance hybrid supercar that combines electrification with Ferrari’s racing heritage.', features: ['Hybrid Powertrain', 'All-Wheel Drive', 'Futuristic Design'], specifications: { engine: '4.0L twin-turbo V8', transmission: '8-speed dual-clutch', drivetrain: 'AWD', weight: '1575 kg', fuelEconomy: 'N/A' } },
    { id: 13, name: 'Tesla Roadster', price: 200000, image: 'https://cdn.motor1.com/images/mgl/G4z31/s1/tesla-roadster.webp', topSpeed: 250, acceleration: '0-60 mph in 1.9s', power: '1,000 hp', type: 'Electric', brand: 'Tesla', description: 'The Tesla Roadster is an all-electric sports car that boasts incredible acceleration and cutting-edge technology.', features: ['All-Electric', 'Autopilot Capability', 'Luxury Interior'], specifications: { engine: 'Electric Motors', transmission: 'Single-speed', drivetrain: 'AWD', weight: 'N/A', fuelEconomy: 'N/A' } },
    { id: 14, name: 'Hennessey Venom F5', price: 2100000, image: 'https://www.supercars.net/blog/wp-content/uploads/2022/01/hennessey-venom-f5-feature-image.jpg', topSpeed: 301, acceleration: '0-60 mph in 2.6s', power: '1,817 hp', type: 'Hypercar', brand: 'Hennessey', description: 'The Hennessey Venom F5 is built to be the fastest car in the world, featuring a lightweight chassis and a powerful twin-turbo V8.', features: ['Extreme Performance', 'Lightweight Carbon Fiber', 'Aerodynamic Efficiency'], specifications: { engine: '6.6L twin-turbo V8', transmission: '7-speed single-clutch', drivetrain: 'RWD', weight: '1360 kg', fuelEconomy: 'N/A' } },
    { id: 15, name: 'SSC Tuatara', price: 2000000, image: 'https://www.topgear.com/sites/default/files/images/news-article/2020/02/5f2fe57b647a177692f8a50e10f47ac4/5e3b44a60aeb122e45fbf8b0_tuatara_08.jpg', topSpeed: 282, acceleration: '0-60 mph in 2.5s', power: '1,750 hp', type: 'Hypercar', brand: 'SSC', description: 'The SSC Tuatara is a high-performance hypercar designed to break speed records and offer exhilarating driving experiences.', features: ['Aerodynamic Design', 'Lightweight Construction', 'Powerful V8 Engine'], specifications: { engine: '5.9L twin-turbo V8', transmission: '7-speed automated manual', drivetrain: 'RWD', weight: '1360 kg', fuelEconomy: 'N/A' } },
    { id: 16, name: 'Rimac C_Two', price: 2100000, image: 'https://static.tecnichenuove.it/electricmotorengineering/2021/01/rimac-c-two.jpg', topSpeed: 258, acceleration: '0-60 mph in 1.85s', power: '1,914 hp', type: 'Electric', brand: 'Rimac', description: 'The Rimac C_Two is a groundbreaking electric hypercar offering blistering speed and cutting-edge technology.', features: ['All-Electric Powertrain', 'Advanced Aerodynamics', 'Lightweight Construction'], specifications: { engine: 'Electric Motors', transmission: 'Single-speed', drivetrain: 'AWD', weight: '1900 kg', fuelEconomy: 'N/A' } },
    { id: 17, name: 'Lotus Evija', price: 2300000, image: 'https://www.topgear.com/sites/default/files/images/cars-road-test/carousel/2021/04/d719e1ed61da07642314fcfc14aa4e47/dsc09964.jpg', topSpeed: 200, acceleration: '0-60 mph in under 3s', power: '1,973 hp', type: 'Electric', brand: 'Lotus', description: 'The Lotus Evija is an all-electric hypercar that embodies cutting-edge technology and lightweight design.', features: ['Electric Powertrain', 'Carbon Fiber Structure', 'Innovative Aerodynamics'], specifications: { engine: 'Electric Motors', transmission: 'Single-speed', drivetrain: 'AWD', weight: '1680 kg', fuelEconomy: 'N/A' } },
    { id: 18, name: 'Zenvo TSR-S', price: 1800000, image: 'https://www.thespeedjournal.com/wp-content/uploads/2021/05/zenvo-trs-s-hypercar-arrives-in-the-uk-05.jpg', topSpeed: 202, acceleration: '0-60 mph in 2.8s', power: '1,177 hp', type: 'Hypercar', brand: 'Zenvo', description: 'The Zenvo TSR-S is a high-performance hypercar with striking design and exhilarating performance.', features: ['Unique Design', 'Powerful V8 Engine', 'Aerodynamic Efficiency'], specifications: { engine: '5.8L supercharged V8', transmission: '7-speed automatic', drivetrain: 'RWD', weight: '1450 kg', fuelEconomy: 'N/A' } },
    { id: 19, name: 'Ferrari F8 Tributo', price: 280000, image: 'https://www.supercars.net/blog/wp-content/uploads/2020/01/ferrari-f8-tributo-01.jpg', topSpeed: 211, acceleration: '0-60 mph in 2.9s', power: '710 hp', type: 'Supercar', brand: 'Ferrari', description: 'The Ferrari F8 Tributo is a powerful supercar that combines elegance with high-performance engineering.', features: ['Turbocharged V8', 'Iconic Design', 'Track-inspired Handling'], specifications: { engine: '3.9L twin-turbo V8', transmission: '7-speed dual-clutch', drivetrain: 'RWD', weight: '1435 kg', fuelEconomy: 'N/A' } },
    { id: 20, name: 'Lamborghini Huracán EVO', price: 261274, image: 'https://cdn.motor1.com/images/mgl/3AOBK/s1/lamborghini-huracan-evo.jpg', topSpeed: 202, acceleration: '0-60 mph in 2.9s', power: '631 hp', type: 'Supercar', brand: 'Lamborghini', description: 'The Lamborghini Huracán EVO is a thrilling supercar known for its aggressive styling and raw power.', features: ['Naturally Aspirated V10', 'Advanced Aerodynamics', 'Innovative Infotainment'], specifications: { engine: '5.2L V10', transmission: '7-speed dual-clutch', drivetrain: 'AWD', weight: '1420 kg', fuelEconomy: 'N/A' } },
    { id: 21, name: 'BMW i8', price: 147500, image: 'https://www.bmwblog.com/wp-content/uploads/2016/12/bmw-i8-frozen-black-edition-2-750x500.jpg', topSpeed: 155, acceleration: '0-60 mph in 4.2s', power: '369 hp', type: 'Hybrid', brand: 'BMW', description: 'The BMW i8 is a plug-in hybrid sports car that merges sustainability with performance.', features: ['Hybrid Powertrain', 'Futuristic Design', 'Aerodynamic Efficiency'], specifications: { engine: '1.5L turbocharged 3-cylinder + electric motors', transmission: '6-speed automatic', drivetrain: 'AWD', weight: '1490 kg', fuelEconomy: '76 MPGe' } },
    { id: 22, name: 'Audi R8', price: 196800, image: 'https://hips.hearstapps.com/hmg-prod/images/2023-audi-r8-gt-rwd-102-1664880871.jpg', topSpeed: 204, acceleration: '0-60 mph in 3.2s', power: '602 hp', type: 'Supercar', brand: 'Audi', description: 'The Audi R8 combines stunning looks with exhilarating performance, featuring a naturally aspirated V10 engine.', features: ['Quattro All-Wheel Drive', 'Iconic Design', 'Luxurious Interior'], specifications: { engine: '5.2L V10', transmission: '7-speed dual-clutch', drivetrain: 'AWD', weight: '1585 kg', fuelEconomy: 'N/A' } },
    { id: 23, name: 'Tesla Model S Plaid', price: 129990, image: 'https://tesla-cdn.thron.com/delivery/public/image/tesla/6f6b5485-6180-41d3-8f60-ff8cf6e8b4b9/bvlatuR/std/2880x1800/_25-Hero-Desktop', topSpeed: 200, acceleration: '0-60 mph in 1.99s', power: '1,020 hp', type: 'Electric', brand: 'Tesla', description: 'The Tesla Model S Plaid is an all-electric sedan known for its record-breaking acceleration and high-tech features.', features: ['Tri-Motor All-Wheel Drive', 'Autopilot Capable', 'Long Range'], specifications: { engine: 'Electric Motors', transmission: 'Single-speed', drivetrain: 'AWD', weight: '2241 kg', fuelEconomy: '117 MPGe' } },
    { id: 24, name: 'Lexus LFA', price: 375000, image: 'https://www.supercars.net/blog/wp-content/uploads/2020/09/lexus-lfa-1.jpg', topSpeed: 202, acceleration: '0-60 mph in 3.6s', power: '552 hp', type: 'Supercar', brand: 'Lexus', description: 'The Lexus LFA is a limited-production supercar that combines luxury with high-performance engineering.', features: ['Naturally Aspirated V10', 'Carbon Fiber Body', 'Exotic Sound'], specifications: { engine: '4.8L V10', transmission: '6-speed automated manual', drivetrain: 'RWD', weight: '1480 kg', fuelEconomy: 'N/A' } },
    { id: 25, name: 'Nissan GT-R NISMO', price: 210740, image: 'https://cdn.motor1.com/images/mgl/xJEJw/s1/2023-nissan-gt-r-nismo.jpg', topSpeed: 205, acceleration: '0-60 mph in 2.9s', power: '600 hp', type: 'Supercar', brand: 'Nissan', description: 'The Nissan GT-R NISMO is a high-performance sports car known for its advanced technology and track capability.', features: ['Twin-Turbo V6', 'Advanced All-Wheel Drive', 'Track-focused Engineering'], specifications: { engine: '3.8L twin-turbo V6', transmission: '6-speed dual-clutch', drivetrain: 'AWD', weight: '1710 kg', fuelEconomy: 'N/A' } },
    { id: 26, name: 'Maserati MC20', price: 210000, image: 'https://cdn.motor1.com/images/mgl/7gkkV/s1/maserati-mc20-2021.jpg', topSpeed: 202, acceleration: '0-60 mph in 2.9s', power: '621 hp', type: 'Supercar', brand: 'Maserati', description: 'The Maserati MC20 is a mid-engine supercar that blends Italian craftsmanship with high-performance dynamics.', features: ['Nettuno Engine', 'Lightweight Carbon Fiber', 'Elegant Design'], specifications: { engine: '3.0L twin-turbo V6', transmission: '8-speed dual-clutch', drivetrain: 'RWD', weight: '1475 kg', fuelEconomy: 'N/A' } },
    { id: 27, name: 'Aston Martin DBS Superleggera', price: 316300, image: 'https://cdn.carbuzz.com/gallery-images/1600/654000/800/654894.jpg', topSpeed: 211, acceleration: '0-60 mph in 3.4s', power: '715 hp', type: 'Supercar', brand: 'Aston Martin', description: 'The Aston Martin DBS Superleggera is a grand tourer that combines luxury and performance in a stunning package.', features: ['V12 Engine', 'Exquisite Design', 'Advanced Technology'], specifications: { engine: '5.2L twin-turbo V12', transmission: '8-speed automatic', drivetrain: 'RWD', weight: '1693 kg', fuelEconomy: 'N/A' } },
    { id: 28, name: 'Jaguar F-Type SVR', price: 123600, image: 'https://motor1.com/images/mgl/Z88QJ/s1/jaguar-f-type-svr.jpg', topSpeed: 200, acceleration: '0-60 mph in 3.5s', power: '575 hp', type: 'Supercar', brand: 'Jaguar', description: 'The Jaguar F-Type SVR offers a perfect blend of performance and style with its powerful engine and iconic design.', features: ['Supercharged V8', 'All-Wheel Drive', 'Sporty Handling'], specifications: { engine: '5.0L supercharged V8', transmission: '8-speed automatic', drivetrain: 'AWD', weight: '1760 kg', fuelEconomy: 'N/A' } },
    { id: 29, name: 'Porsche Taycan Turbo S', price: 185000, image: 'https://hips.hearstapps.com/hmg-prod/images/2020-porsche-taycan-turbo-s-101-1597800300.jpg', topSpeed: 161, acceleration: '0-60 mph in 2.6s', power: '750 hp', type: 'Electric', brand: 'Porsche', description: 'The Porsche Taycan Turbo S is an electric sports car that delivers exhilarating performance and cutting-edge technology.', features: ['Electric All-Wheel Drive', 'High-Performance Battery', 'Luxury Interior'], specifications: { engine: 'Electric Motors', transmission: '2-speed automatic', drivetrain: 'AWD', weight: '2290 kg', fuelEconomy: 'N/A' } },
    { id: 30, name: 'Bentley Continental GT Speed', price: 240800, image: 'https://cdn.motor1.com/images/mgl/EMPEP/s1/bentley-continental-gt-speed.jpg', topSpeed: 208, acceleration: '0-60 mph in 3.5s', power: '650 hp', type: 'Luxury', brand: 'Bentley', description: 'The Bentley Continental GT Speed combines luxury and performance, providing an unparalleled driving experience.', features: ['W12 Engine', 'Lavish Interior', 'Advanced Infotainment'], specifications: { engine: '6.0L twin-turbo W12', transmission: '8-speed dual-clutch', drivetrain: 'AWD', weight: '2240 kg', fuelEconomy: 'N/A' } },
    { id: 31, name: 'Rolls-Royce Wraith', price: 343350, image: 'https://www.supercars.net/blog/wp-content/uploads/2021/05/rolls-royce-wraith-2021.jpg', topSpeed: 155, acceleration: '0-60 mph in 4.4s', power: '624 hp', type: 'Luxury', brand: 'Rolls-Royce', description: 'The Rolls-Royce Wraith is a luxurious grand tourer that combines performance with bespoke craftsmanship.', features: ['V12 Engine', 'Luxurious Interior', 'State-of-the-Art Technology'], specifications: { engine: '6.6L twin-turbo V12', transmission: '8-speed automatic', drivetrain: 'RWD', weight: '2070 kg', fuelEconomy: 'N/A' } },
    { id: 32, name: 'McLaren 720S', price: 299000, image: 'https://cdn.carbuzz.com/gallery-images/1600/654000/800/654741.jpg', topSpeed: 212, acceleration: '0-60 mph in 2.8s', power: '710 hp', type: 'Supercar', brand: 'McLaren', description: 'The McLaren 720S is a lightweight supercar that delivers blistering performance and advanced aerodynamics.', features: ['Twin-Turbo V8', 'Monocage II Carbon Fiber Structure', 'Active Aerodynamics'], specifications: { engine: '4.0L twin-turbo V8', transmission: '7-speed dual-clutch', drivetrain: 'RWD', weight: '1418 kg', fuelEconomy: 'N/A' } },
    { id: 33, name: 'Ferrari Portofino M', price: 226000, image: 'https://cdn.motor1.com/images/mgl/1k6jX/s1/ferrari-portofino-m.jpg', topSpeed: 199, acceleration: '0-60 mph in 3.5s', power: '612 hp', type: 'Grand Tourer', brand: 'Ferrari', description: 'The Ferrari Portofino M is a versatile grand tourer that offers performance, comfort, and style.', features: ['Turbocharged V8', 'Convertible Design', 'Advanced Infotainment'], specifications: { engine: '3.9L twin-turbo V8', transmission: '7-speed dual-clutch', drivetrain: 'RWD', weight: '1670 kg', fuelEconomy: 'N/A' } },
    { id: 34, name: 'Lamborghini Urus', price: 222004, image: 'https://hips.hearstapps.com/hmg-prod/images/lamborghini-urus-104-1547841240.jpg', topSpeed: 190, acceleration: '0-60 mph in 3.6s', power: '641 hp', type: 'SUV', brand: 'Lamborghini', description: 'The Lamborghini Urus is a luxury SUV that combines high performance with the practicality of an everyday vehicle.', features: ['V8 Engine', 'Dynamic Steering', 'Spacious Interior'], specifications: { engine: '4.0L twin-turbo V8', transmission: '8-speed automatic', drivetrain: 'AWD', weight: '2200 kg', fuelEconomy: 'N/A' } },
    { id: 35, name: 'Audi RS Q8', price: 114500, image: 'https://cdn.carbuzz.com/gallery-images/1600/654000/800/654789.jpg', topSpeed: 190, acceleration: '0-60 mph in 3.7s', power: '591 hp', type: 'SUV', brand: 'Audi', description: 'The Audi RS Q8 is a high-performance SUV that delivers sports car dynamics with everyday practicality.', features: ['V8 Engine', 'Quattro All-Wheel Drive', 'Luxurious Interior'], specifications: { engine: '4.0L twin-turbo V8', transmission: '8-speed automatic', drivetrain: 'AWD', weight: '2300 kg', fuelEconomy: 'N/A' } },
    { id: 36, name: 'Maserati Levante Trofeo', price: 153100, image: 'https://cdn.motor1.com/images/mgl/pPL0J/s1/maserati-levante-trofeo-2021.jpg', topSpeed: 187, acceleration: '0-60 mph in 3.8s', power: '590 hp', type: 'SUV', brand: 'Maserati', description: 'The Maserati Levante Trofeo combines luxury and performance in a versatile SUV package.', features: ['Twin-Turbo V8', 'All-Wheel Drive', 'Premium Materials'], specifications: { engine: '3.8L twin-turbo V8', transmission: '8-speed automatic', drivetrain: 'AWD', weight: '2240 kg', fuelEconomy: 'N/A' } },
    { id: 37, name: 'Alfa Romeo Giulia Quadrifoglio', price: 77845, image: 'https://cdn.motor1.com/images/mgl/xJG6E/s1/alfa-romeo-giulia-quadrifoglio-2020.jpg', topSpeed: 191, acceleration: '0-60 mph in 3.8s', power: '505 hp', type: 'Sedan', brand: 'Alfa Romeo', description: 'The Alfa Romeo Giulia Quadrifoglio is a performance sedan that delivers exhilarating driving dynamics and Italian style.', features: ['Twin-Turbo V6', 'Lightweight Construction', 'Driver-Focused Cabin'], specifications: { engine: '2.9L twin-turbo V6', transmission: '8-speed automatic', drivetrain: 'RWD', weight: '1580 kg', fuelEconomy: 'N/A' } },
    { id: 38, name: 'Dodge Charger SRT Hellcat Redeye', price: 79995, image: 'https://hips.hearstapps.com/hmg-prod/images/2021-dodge-charger-srt-hellcat-redeye-widebody-101-1622582900.jpg', topSpeed: 203, acceleration: '0-60 mph in 3.6s', power: '797 hp', type: 'Sedan', brand: 'Dodge', description: 'The Dodge Charger SRT Hellcat Redeye is a high-performance sedan that combines muscular power with everyday usability.', features: ['Supercharged V8', 'All-Wheel Drive', 'Aggressive Styling'], specifications: { engine: '6.2L supercharged HEMI V8', transmission: '8-speed automatic', drivetrain: 'AWD', weight: '2040 kg', fuelEconomy: 'N/A' } },
    { id: 38, name: 'Dodge Charger SRT Hellcat Redeye', price: 79995, image: 'https://hips.hearstapps.com/hmg-prod/images/2021-dodge-charger-srt-hellcat-redeye-widebody-101-1622582900.jpg', topSpeed: 203, acceleration: '0-60 mph in 3.6s', power: '797 hp', type: 'Sedan', brand: 'Dodge', description: 'The Dodge Charger SRT Hellcat Redeye is a high-performance sedan that combines muscular power with everyday usability.', features: ['Supercharged V8', 'All-Wheel Drive', 'Aggressive Styling'], specifications: { engine: '6.2L supercharged HEMI V8', transmission: '8-speed automatic', drivetrain: 'AWD', weight: '2040 kg', fuelEconomy: 'N/A' } },
    { id: 39, name: 'Ford Mustang Shelby GT500', price: 79800, image: 'https://cdn.carbuzz.com/gallery-images/1600/654000/800/654652.jpg', topSpeed: 180, acceleration: '0-60 mph in 3.5s', power: '760 hp', type: 'Muscle Car', brand: 'Ford', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 40, name: 'Chevrolet Camaro ZL1', price: 63000, image: 'https://cdn.motor1.com/images/mgl/vQbvP/s1/chevrolet-camaro-zl1.jpg', topSpeed: 198, acceleration: '0-60 mph in 3.5s', power: '650 hp', type: 'Muscle Car', brand: 'Chevrolet', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 41, name: 'Dodge Challenger SRT Hellcat', price: 61645, image: 'https://cdn.motor1.com/images/mgl/xQJpR/s1/2022-dodge-challenger-srt-hellcat-redeye.jpg', topSpeed: 203, acceleration: '0-60 mph in 3.6s', power: '717 hp', type: 'Muscle Car', brand: 'Dodge', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 42, name: 'BMW M4 Competition', price: 76900, image: 'https://cdn.carbuzz.com/gallery-images/1600/654000/800/654651.jpg', topSpeed: 180, acceleration: '0-60 mph in 3.8s', power: '503 hp', type: 'Coupe', brand: 'BMW', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 43, name: 'Mercedes-AMG C63 S Coupe', price: 78950, image: 'https://hips.hearstapps.com/hmg-prod/images/2020-mercedes-amg-c63-s-coupe-103-1599144487.jpg', topSpeed: 180, acceleration: '0-60 mph in 3.7s', power: '503 hp', type: 'Coupe', brand: 'Mercedes-Benz', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 44, name: 'Cadillac CT5-V Blackwing', price: 83995, image: 'https://cdn.motor1.com/images/mgl/pQ66P/s1/cadillac-ct5-v-blackwing.jpg', topSpeed: 200, acceleration: '0-60 mph in 3.7s', power: '668 hp', type: 'Sedan', brand: 'Cadillac', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 45, name: 'Jaguar XE SV Project 8', price: 187500, image: 'https://cdn.motor1.com/images/mgl/R11gA/s1/2020-jaguar-xe-sv-project-8.jpg', topSpeed: 200, acceleration: '0-60 mph in 3.3s', power: '592 hp', type: 'Sedan', brand: 'Jaguar', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 46, name: 'Audi RS7 Sportback', price: 114000, image: 'https://cdn.motor1.com/images/mgl/kOlkb/s1/2020-audi-rs7.jpg', topSpeed: 190, acceleration: '0-60 mph in 3.5s', power: '591 hp', type: 'Sedan', brand: 'Audi', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 47, name: 'Porsche Panamera Turbo S', price: 179800, image: 'https://hips.hearstapps.com/hmg-prod/images/2021-porsche-panamera-turbo-s-101-1600222951.jpg', topSpeed: 196, acceleration: '0-60 mph in 2.9s', power: '620 hp', type: 'Sedan', brand: 'Porsche', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 48, name: 'Bentley Flying Spur', price: 214600, image: 'https://cdn.motor1.com/images/mgl/WORlJ/s1/bentley-flying-spur.jpg', topSpeed: 207, acceleration: '0-60 mph in 3.7s', power: '626 hp', type: 'Luxury', brand: 'Bentley', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 49, name: 'Rolls-Royce Ghost', price: 332500, image: 'https://cdn.motor1.com/images/mgl/2RvvA/s1/2021-rolls-royce-ghost.jpg', topSpeed: 155, acceleration: '0-60 mph in 4.6s', power: '563 hp', type: 'Luxury', brand: 'Rolls-Royce', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
    { id: 50, name: 'Aston Martin Vantage', price: 142086, image: 'https://cdn.motor1.com/images/mgl/MZVVv/s1/2021-aston-martin-vantage.jpg', topSpeed: 195, acceleration: '0-60 mph in 3.5s', power: '503 hp', type: 'Coupe', brand: 'Aston Martin', description: '', features: [], specifications: { engine: '', transmission: '', drivetrain: '', weight: '', fuelEconomy: '' } },
]

app.get('/', (req: Request, res: Response) => {
    res.send(fullData)
})
app.get('/catalog', (req: Request, res: Response) => {
    res.send(fullData)
})
app.post('/catalog', (req: Request, res: Response) => {
     const newCar = req.body
     newCar.id = fullData.length + 1
     fullData.push(newCar)
     console.log(fullData)
     res.send(newCar)
})
app.delete('/catalog', (req: Request, res: Response) => {
    const {name} = req.body
    if(!name){
        return res.status(404).send('This object does not have a name or other requried properties.')
    }
    const modifiedData = fullData.filter(name => {name == })
})
app.listen(3500, (error: Error) => {
    if(error){
        console.log(`error following: ${error}`)
    }
    console.log('Server is running on port 3500')
})
